const Products=[
    {
      asin: "B0CWXNS552",
      climate_pledge_friendly: false,
      currency: "USD",
      delivery: "FREE delivery Thu, Aug 22 on $35 of items shipped by AmazonOr fastest delivery Tue, Aug 20",
      has_variations: false,
      is_amazon_choice: true,
      is_best_seller: false,
      is_prime: true,
      product_minimum_offer_price: "$22.82",
      product_num_offers: 4,
      product_num_ratings: 5850,
      product_original_price: "$29.00",
      product_photo: "https://m.media-amazon.com/images/I/71rP7f78eFL._AC_UL960_FMwebp_QL65_.jpg",
      product_price: "$24.99",
      product_star_rating: "4.6",
      product_title: "Apple AirTag",
      product_url: "https://www.amazon.com/dp/B0CWXNS552",
      sales_volume: "10K+ bought in past month"
    },
    {
      asin: "B0D54JZTHY",
      climate_pledge_friendly: false,
      currency: "USD",
      delivery: "FREE delivery Thu, Aug 22 Or fastest delivery Tue, Aug 20",
      has_variations: false,
      is_amazon_choice: false,
      is_best_seller: false,
      is_prime: true,
      product_minimum_offer_price: "$76.79",
      product_num_offers: 3,
      product_num_ratings: 977,
      product_original_price: "$99.00",
      product_photo: "https://m.media-amazon.com/images/I/61bMNCeAUAL._AC_UL960_FMwebp_QL65_.jpg",
      product_price: "$79.99",
      product_star_rating: "4.7",
      product_title: "Apple AirTag 4 Pack",
      product_url: "https://www.amazon.com/dp/B0D54JZTHY",
      sales_volume: "10K+ bought in past month"
    },
    {
      asin: "B0CRCWCGNW",
      climate_pledge_friendly: false,
      currency: "USD",
      delivery: "FREE delivery Thu, Aug 22 on $35 of items shipped by AmazonOr fastest delivery Tue, Aug 20",
      has_variations: false,
      is_amazon_choice: false,
      is_best_seller: false,
      is_prime: true,
      product_minimum_offer_price: "$0.25",
      product_num_offers: 1,
      product_num_ratings: 8149,
      product_original_price: null,
      product_photo: "https://m.media-amazon.com/images/I/713QRmQtrcL._AC_UL960_FMwebp_QL65_.jpg",
      product_price: "$0.25",
      product_star_rating: "4.7",
      product_title: "Amazon Basics Purple Washable School Glue Sticks, Dries Clear, 0.21-oz Stick, 2-Pack",
      product_url: "https://www.amazon.com/dp/B0CRCWCGNW",
      sales_volume: "60K+ bought in past month",
      unit_count: 0,
      unit_price: "$0.59"
    },
    {
      asin: "B0CRB1VZ46",
      climate_pledge_friendly: false,
      currency: "USD",
      delivery: "FREE delivery Thu, Aug 22 on $35 of items shipped by AmazonOr fastest delivery Tue, Aug 20",
      has_variations: false,
      is_amazon_choice: false,
      is_best_seller: true,
      is_prime: true,
      product_minimum_offer_price: "$2.39",
      product_num_offers: 1,
      product_num_ratings: 55143,
      product_original_price: null,
      product_photo: "https://m.media-amazon.com/images/I/51XUXWgWF8L._AC_UL960_FMwebp_QL65_.jpg",
      product_price: "$2.39",
      product_star_rating: "4.8",
      product_title: "Amazon Basics Multipurpose, Comfort Grip, PVD Coated, Stainless Steel Office Scissors, Grey 1 pack",
      product_url: "https://www.amazon.com/dp/B0CRB1VZ46",
      sales_volume: "50K+ bought in past month"
    },
    {
      asin: "B0CRDYZVDC",
      climate_pledge_friendly: false,
      currency: "USD",
      delivery: "FREE delivery Thu, Aug 22 on $35 of items shipped by AmazonOr fastest delivery Wed, Aug 21",
      has_variations: false,
      is_amazon_choice: false,
      is_best_seller: true,
      is_prime: true,
      product_minimum_offer_price: "$0.49",
      product_num_offers: 1,
      product_num_ratings: 13837,
      product_original_price: null,
      product_photo: "https://m.media-amazon.com/images/I/61aub4rRv9L._AC_UL960_FMwebp_QL65_.jpg",
      product_price: "$0.49",
      product_star_rating: "4.8",
      product_title: "Amazon Basics Heavy Duty Plastic Folders with 2 Pockets for Letter Size Paper, Red and Blue, 2-Pack",
      product_url: "https://www.amazon.com/dp/B0CRDYZVDC",
      sales_volume: "100K+ bought in past month",
      unit_count: 2,
      unit_price: "$0.25"
    },
    {
      asin: "B0BVDJ293G",
      climate_pledge_friendly: false,
      currency: "USD",
      delivery: "Available instantly",
      has_variations: false,
      is_amazon_choice: false,
      is_best_seller: true,
      is_prime: false,
      product_minimum_offer_price: "$0.00",
      product_num_offers: 1,
      product_num_ratings: 226643,
      product_original_price: "$25.79",
      product_photo: "https://m.media-amazon.com/images/I/A15A7wamBML._AC_UL960_FMwebp_QL65_.jpg",
      product_price: "$0.00",
      product_star_rating: "4.8",
      product_title: "Fourth Wing: Empyrean, Book 1",
      product_url: "https://www.amazon.com/dp/B0BVDJ293G",
      sales_volume: "Other formats: "
    }
]
  export default Products;